import os
import csv
import argparse
import logging
from pathlib import Path
import rdflib
from lxml import etree


TASK_LABEL_DEFAULT = '3_5'
DOMAIN_DEFAULT     = 'Generic'


def discover_triples(owl_dir: Path, rdf_dir: Path):
    triples = []
    for fname in os.listdir(str(rdf_dir)):
        if not fname.lower().endswith('.rdf'):
            continue
        base = fname[:-4]
        if '-' not in base:
            continue
        n1, n2 = base.split('-', 1)
        o1 = owl_dir / f"{n1}.owl"
        o2 = owl_dir / f"{n2}.owl"
        r  = rdf_dir / fname
        if o1.exists() and o2.exists():
            triples.append((o1, o2, r))
        else:
            logging.warning(f"Missing OWL for {fname}: "
                            f"{str(o1) if not o1.exists() else ''} "
                            f"{str(o2) if not o2.exists() else ''}")
    return triples

def iri_to_label(iri: str) -> str:
    """take the part after the last '#' or '/'"""
    if '#' in iri:
        return iri.split('#')[-1]
    return iri.rsplit('/', 1)[-1]

def extract_classes(owl_file_path: Path):
    """
    Parse an OWL/XML file and return two lists:
      - class_iris   : full IRIs of owl:Class
      - class_labels : their local names, filtered to drop long random IDs
    """
    g = rdflib.Graph()
    g.parse(str(owl_file_path), format='xml')

    iris, labels = [], []
    for subj in g.subjects(rdflib.RDF.type, rdflib.OWL.Class):
        # skip blank nodes
        if not isinstance(subj, rdflib.URIRef):
            continue
        iri   = str(subj)
        label = iri_to_label(iri)
        # drop anything that looks like a long hash / autogenerated ID
        if len(label) > 20:
            continue
        iris.append(iri)
        labels.append(label)
    return iris, labels

def parse_alignment_labels(alignment_file_path: Path):
    """
    Parse an Alignment RDF file (OAEI format) and return a list of
    (label1, label2) for each mapping.
    """
    ns = {
        'al': 'http://knowledgeweb.semanticweb.org/heterogeneity/alignment',
        'rdf': 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
    }
    tree  = etree.parse(str(alignment_file_path))
    cells = tree.xpath('//al:Cell', namespaces=ns)

    pairs = []
    for cell in cells:
        e1 = cell.xpath('al:entity1/@rdf:resource', namespaces=ns)[0]
        e2 = cell.xpath('al:entity2/@rdf:resource', namespaces=ns)[0]
        l1 = iri_to_label(e1)
        l2 = iri_to_label(e2)
        # skip if either label is a long autogenerated ID
        if len(l1) > 20 or len(l2) > 20:
            continue
        pairs.append((l1, l2))
    return pairs

def write_csv(rows, output_csv: Path):
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ['question', 'answer', 'task_label', 'domain', 'source_file', 'labels']
    with output_csv.open('w', encoding='utf-8-sig', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow({k: r.get(k, '') for k in fieldnames})


def main():
    parser = argparse.ArgumentParser(description='Generate ontology alignment tasks (class alignment) from OAEI alignment files.')
    parser.add_argument('--owl-dir', type=str, required=True, help='Directory containing .owl files (names used in RDF alignments).')
    parser.add_argument('--rdf-dir', type=str, required=True, help='Directory containing .rdf alignment files (OAEI format).')
    parser.add_argument('--output-csv', type=str, required=True, help='Path to output CSV.')
    parser.add_argument('--task-label', type=str, default=TASK_LABEL_DEFAULT, help='Task label to include in rows.')
    parser.add_argument('--domain', type=str, default=DOMAIN_DEFAULT, help='Domain label to include in rows.')
    parser.add_argument('--log', type=str, default='info', help='Logging level: debug, info, warning, error.')

    args = parser.parse_args()
    level = getattr(logging, args.log.upper(), logging.INFO)
    logging.basicConfig(level=level, format='%(asctime)s %(levelname)s: %(message)s')

    owl_dir = Path(args.owl_dir)
    rdf_dir = Path(args.rdf_dir)
    output_csv = Path(args.output_csv)

    rows = []
    for o1, o2, rdf in discover_triples(owl_dir, rdf_dir):
        _, labels1 = extract_classes(o1)
        _, labels2 = extract_classes(o2)
        question = (
            "Please align the classes between these two ontologies:\n"
            f"- Ontology 1 classes: {labels1}\n"
            f"- Ontology 2 classes: {labels2}"
        )
        answer = parse_alignment_labels(rdf)
        rows.append({
            'question'    : question,
            'answer'      : str(answer),
            'task_label'  : args.task_label,
            'domain'      : args.domain,
            'source_file' : rdf.name,
            'labels'      : str(labels1 + labels2),
        })

    write_csv(rows, output_csv)
    logging.info(f"Generated CSV: {output_csv}")


if __name__ == '__main__':
    main()